#!/bin/bash

. $(dirname $0)/meta-common

components=$*

for c in $components; do
    name=$(echo $c | tr -c '[:alnum:]' '_')

    echo export ${name}ver=$(get_version $c)
	echo export ${name}rev=$(get_revision $c)
done

