#!/bin/bash

selfdir=$(readlink -f $(dirname $0))

. $selfdir/rel-common

function print_usage {
    echo "
Usage: $0 [OPTIONS] COMMAND

where OPTIONS is a combination of:
    v           add verbosity

and COMMAND is one of:
    help        print this help
    versions    print version of each component
    env         generate environment
"
}

## parse command line

verbose=0
while getopts "v" opt; do
    case $opt in
        v)  verbose=1
        ;;
        \?) print_usage
            exit 1
        ;;
    esac
done

shift $(($OPTIND-1))
cmd=$1
shift 1

case $cmd in
    versions)
        action="$selfdir/rel-versions"
    ;;
    env)
        action="$selfdir/rel-env"
    ;;
    *)
        print_usage
        exit 1
    ;;
esac

## execute action

components=$(find . -maxdepth 1 -type d -not -name '.*' -printf '%f\n')
printv "components: $components"

export components
export verbose
$action $*

